sudo: required
services:
  - doker

before_install:
  - docker build -t nikitakrasavtsev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nikitakrasavtsev/docker-react npm run test -- --coverage
